-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admin_actions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  applicant_id uuid NOT NULL,
  action_type text NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  performed_by uuid,
  CONSTRAINT admin_actions_pkey PRIMARY KEY (id),
  CONSTRAINT admin_actions_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES public.applicants(id)
);
CREATE TABLE public.admin_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  name character varying,
  role character varying DEFAULT 'admin'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  last_login_at timestamp with time zone,
  company_name character varying DEFAULT 'AutoIntel Recruitment'::character varying,
  timezone character varying DEFAULT 'Asia/Manila'::character varying,
  date_format character varying DEFAULT 'MM/DD/YYYY'::character varying,
  language character varying DEFAULT 'en'::character varying,
  email_new_applicant boolean DEFAULT true,
  email_assessment_complete boolean DEFAULT true,
  email_daily_digest boolean DEFAULT false,
  browser_notifications boolean DEFAULT true,
  webhook character varying,
  two_factor_auth boolean DEFAULT false,
  password_expiry character varying DEFAULT '90'::character varying,
  session_timeout character varying DEFAULT '30'::character varying,
  ip_whitelist text,
  resume_weight integer DEFAULT 40,
  video_weight integer DEFAULT 35,
  profile_weight integer DEFAULT 25,
  auto_reject_threshold integer DEFAULT 30,
  auto_shortlist_threshold integer DEFAULT 85,
  theme character varying DEFAULT 'light'::character varying,
  sidebar_collapsed boolean DEFAULT false,
  compact_view boolean DEFAULT false,
  data_retention character varying DEFAULT '365'::character varying,
  auto_archive boolean DEFAULT true,
  api_access boolean DEFAULT false,
  debug_mode boolean DEFAULT false,
  slack_webhook text,
  CONSTRAINT admin_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.applicants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  name text NOT NULL,
  position text NOT NULL,
  access_token text NOT NULL UNIQUE,
  access_expires_at timestamp with time zone NOT NULL,
  rules_accepted boolean DEFAULT false,
  rules_accepted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  photo_url text,
  resume_text text,
  parsed_resume_json jsonb DEFAULT '{}'::jsonb,
  video_path text,
  transcription_text text,
  applied_job_id text,
  screening_score numeric,
  screening_fit_category text,
  overall_score numeric,
  status text DEFAULT 'pending_screening'::text,
  updated_at timestamp with time zone DEFAULT now(),
  rejection_reason text,
  duplicate_matches jsonb,
  duplicate_detected_at timestamp with time zone,
  duplicate_layer integer,
  screening_status text DEFAULT 'needs_review'::text,
  screening_stage text DEFAULT 'screened'::text,
  screened_at timestamp with time zone,
  hr_notes text,
  decision_date timestamp with time zone,
  decision_notes text,
  offer_email_sent boolean DEFAULT false,
  offer_email_sent_at timestamp with time zone,
  offer_attachment_url text,
  rejection_email_sent boolean DEFAULT false,
  rejection_email_sent_at timestamp with time zone,
  CONSTRAINT applicants_pkey PRIMARY KEY (id),
  CONSTRAINT applicants_applied_job_id_fkey FOREIGN KEY (applied_job_id) REFERENCES public.job_postings(job_id)
);
CREATE TABLE public.hr_managers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  role character varying DEFAULT 'Manager'::character varying,
  department character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hr_managers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.job_postings (
  job_id text NOT NULL,
  title text NOT NULL,
  department text,
  skills jsonb DEFAULT '[]'::jsonb,
  keywords jsonb DEFAULT '[]'::jsonb,
  required_education jsonb DEFAULT '[]'::jsonb,
  expected_projects jsonb DEFAULT '[]'::jsonb,
  preferred_certifications jsonb DEFAULT '[]'::jsonb,
  min_years_experience numeric,
  max_years_experience numeric,
  created_at timestamp with time zone DEFAULT now(),
  source text NOT NULL DEFAULT 'admin'::text CHECK (source = ANY (ARRAY['dataset'::text, 'admin'::text])),
  is_active boolean DEFAULT true,
  deleted_at timestamp with time zone,
  description text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_postings_pkey PRIMARY KEY (job_id)
);
CREATE TABLE public.resume_scores (
  score_id uuid NOT NULL DEFAULT gen_random_uuid(),
  applicant_id uuid NOT NULL,
  job_id text NOT NULL,
  experience_score numeric CHECK (experience_score >= 0::numeric AND experience_score <= 100::numeric),
  skills_score numeric CHECK (skills_score >= 0::numeric AND skills_score <= 100::numeric),
  education_score numeric CHECK (education_score >= 0::numeric AND education_score <= 100::numeric),
  project_score numeric CHECK (project_score >= 0::numeric AND project_score <= 100::numeric),
  final_score numeric CHECK (final_score >= 0::numeric AND final_score <= 100::numeric),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in_review'::text, 'shortlisted'::text, 'rejected'::text, 'hired'::text])),
  match_explain jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT resume_scores_pkey PRIMARY KEY (score_id),
  CONSTRAINT resume_scores_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES public.applicants(id),
  CONSTRAINT resume_scores_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.job_postings(job_id)
);
CREATE TABLE public.resumes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  applicant_id uuid NOT NULL,
  resume_url text,
  status text DEFAULT 'pending'::text,
  uploaded_at timestamp with time zone DEFAULT now(),
  extracted_text text,
  named_entities jsonb,
  ner_score numeric,
  processing_status text DEFAULT 'pending'::text,
  text_extracted_at timestamp with time zone,
  ner_processed_at timestamp with time zone,
  raw_extracted_content text,
  parsed_data jsonb,
  ner_status text DEFAULT 'pending'::text,
  extraction_metadata jsonb,
  pre_ner_sections jsonb,
  cleaned_resume_text text,
  gpt_cleaning_status text DEFAULT 'pending'::text,
  extractor_used text,
  CONSTRAINT resumes_pkey PRIMARY KEY (id),
  CONSTRAINT resumes_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES public.applicants(id)
);
CREATE TABLE public.scheduled_interviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  applicant_id uuid NOT NULL,
  interviewer_id uuid,
  job_id text,
  interview_date date NOT NULL,
  interview_time time without time zone NOT NULL,
  interview_type text NOT NULL CHECK (interview_type = ANY (ARRAY['online'::text, 'in-person'::text])),
  meeting_link text,
  meeting_passcode text,
  location text,
  status text DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'completed'::text, 'cancelled'::text])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  meeting_id text,
  duration_minutes integer DEFAULT 60,
  time_zone text DEFAULT 'Asia/Manila'::text,
  primary_interviewer_email text,
  additional_attendees jsonb DEFAULT '[]'::jsonb,
  applicant_instructions text,
  internal_notes text,
  calendar_event_id text,
  ics_uid text,
  CONSTRAINT scheduled_interviews_pkey PRIMARY KEY (id),
  CONSTRAINT scheduled_interviews_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES public.applicants(id),
  CONSTRAINT scheduled_interviews_interviewer_id_fkey FOREIGN KEY (interviewer_id) REFERENCES public.hr_managers(id),
  CONSTRAINT scheduled_interviews_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.job_postings(job_id)
);
CREATE TABLE public.scoring_settings (
  settings_id uuid NOT NULL DEFAULT gen_random_uuid(),
  experience_weight numeric NOT NULL DEFAULT 40 CHECK (experience_weight >= 0::numeric),
  skills_weight numeric NOT NULL DEFAULT 30 CHECK (skills_weight >= 0::numeric),
  education_weight numeric NOT NULL DEFAULT 20 CHECK (education_weight >= 0::numeric),
  projects_weight numeric NOT NULL DEFAULT 10 CHECK (projects_weight >= 0::numeric),
  qualified_threshold numeric NOT NULL DEFAULT 80 CHECK (qualified_threshold >= 0::numeric AND qualified_threshold <= 100::numeric),
  review_threshold numeric NOT NULL DEFAULT 60 CHECK (review_threshold >= 0::numeric AND review_threshold <= 100::numeric),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  traincert_weight numeric DEFAULT 6 CHECK (traincert_weight >= 0::numeric AND traincert_weight <= 100::numeric),
  achievements_weight numeric DEFAULT 4 CHECK (achievements_weight >= 0::numeric AND achievements_weight <= 100::numeric),
  baseline_experience numeric DEFAULT 2 CHECK (baseline_experience >= 0::numeric),
  baseline_skills numeric DEFAULT 8 CHECK (baseline_skills >= 0::numeric),
  baseline_education numeric DEFAULT 2 CHECK (baseline_education >= 0::numeric),
  baseline_projects numeric DEFAULT 2 CHECK (baseline_projects >= 0::numeric),
  baseline_traincert numeric DEFAULT 2 CHECK (baseline_traincert >= 0::numeric),
  baseline_achievements numeric DEFAULT 1 CHECK (baseline_achievements >= 0::numeric),
  scoring_type text DEFAULT 'hybrid'::text CHECK (scoring_type = ANY (ARRAY['semantic'::text, 'hybrid'::text])),
  resume_weight integer DEFAULT 50,
  video_weight integer DEFAULT 40,
  profile_weight integer DEFAULT 10,
  requirement_weight integer DEFAULT 60,
  count_weight integer DEFAULT 40,
  CONSTRAINT scoring_settings_pkey PRIMARY KEY (settings_id)
);
CREATE TABLE public.video_assessments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  applicant_id uuid NOT NULL,
  video_url text,
  status text DEFAULT 'pending'::text,
  submitted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  transcription text,
  transcription_status character varying DEFAULT 'pending'::character varying,
  transcription_error text,
  transcribed_at timestamp with time zone,
  transcription_segments jsonb,
  video_duration_seconds integer,
  transcript_word_count integer,
  transcript_score numeric,
  relevance_score numeric,
  experience_score numeric,
  skills_score numeric,
  completeness_score numeric,
  validation_status character varying DEFAULT 'pending'::character varying,
  validation_message text,
  scored_at timestamp with time zone,
  CONSTRAINT video_assessments_pkey PRIMARY KEY (id),
  CONSTRAINT video_assessments_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES public.applicants(id)
);
CREATE TABLE public.work_style_assessments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  applicant_id uuid NOT NULL,
  answers jsonb DEFAULT '[]'::jsonb,
  dimension_scores jsonb DEFAULT '[]'::jsonb,
  work_style_alignment_score integer,
  matched_role text,
  status text DEFAULT 'pending'::text,
  submitted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  semantic_score numeric,
  role_family character varying,
  strong_areas jsonb,
  moderate_areas jsonb,
  development_areas jsonb,
  essay_insights text,
  scoring_method character varying DEFAULT 'semantic'::character varying,
  scored_at timestamp with time zone,
  essay text,
  CONSTRAINT work_style_assessments_pkey PRIMARY KEY (id),
  CONSTRAINT work_style_assessments_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES public.applicants(id)
);